# Generated by Django 6.0.1 on 2026-01-28 02:05

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_pleasure", models.BooleanField(default=False)),
                (
                    "periodicity",
                    models.IntegerField(
                        choices=[
                            (1, "Раз в неделю"),
                            (2, "Два раза в неделю"),
                            (3, "Три раза в неделю"),
                            (7, "Ежедневно"),
                        ],
                        default=1,
                        validators=[habits.validators.validate_periodicity],
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "time_spent_minutes",
                    models.PositiveSmallIntegerField(validators=[habits.validators.validate_max_two_minutes]),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="habits.habit",
                        validators=[habits.validators.validate_linked_habit_is_pleasure],
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="habits", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
