# Generated by Django 5.2.10 on 2026-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
